### ISSUE TITLE
Possible bug in token normalizer calculation 

### ISSUE THREAD

**Issue by talolard** [mimno/jsLDA#11]
Shouldn't the last plus on the last line be a minus because  we just removed the topic from this token
https://github.com/mimno/jsLDA/blob/4bb520ba157ff5b8a80b88a03785ca181364d950/jslda.js#L370

**Comment by mimno** [comment]
No, the effect of the token is removed in the previous line, and added back for the new topic at the bottom of the loop. Subtracting could lead to a negative probability.
