### ISSUE TITLE
Parameter question

### ISSUE THREAD

**Issue by owendall** [mimno/jsLDA#5]
var correlationCutoff = 0.25; 

Should the parameter "cutoff" in the function getCorrelationGraph actually be "correlationCuttoff"?

 "function var getCorrelationGraph = function(correlationMatrix, cutoff)"

**Comment by mimno** [comment]
In this case `cutoff` is a local variable for the function, so I do want to make it clear that it's a different variable. But `correlationCutoff` is also not being used, which isn't great. At some point I switched from correlation to pointwise mutual information, which has a different scale. The default cutoff is -100.0, which is hard-coded when the function is actually executed.

**Comment by owendall** [comment]
Ahh, Gotcha. Thanks for that....
